// Seeds the Dallas–Fort Worth launch metro per PRD §12.2.
// Facility names are fictional; geography is real DFW.
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function daysFromNow(days: number, hour = 8): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d;
}

const listings = [
  {
    name: "Trinity Pines Golf Club",
    type: "course",
    description:
      "Public 18-hole course with a dedicated junior program. Juniors play free after 3pm with a paying adult. PGA Jr. League host site with a six-hole short course perfect for beginners.",
    address: "4200 Riverbend Dr",
    city: "Dallas",
    state: "TX",
    zip: "75204",
    lat: 32.8121,
    lng: -96.7695,
    phone: "(214) 555-0142",
    website: "https://example.com/trinity-pines",
    hours: "Daily 6:30am–8pm",
    ageMin: 5,
    ageMax: 18,
    skillLevels: "beginner,intermediate,competitive",
    priceTier: 2,
    programs: "lessons,leagues,tournaments",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-20),
    reviews: [
      {
        authorName: "Melissa T.",
        rating: 5,
        body: "The junior clinic on Saturdays is fantastic. Coach kept all eight kids engaged for the full hour and my 7-year-old begged to come back.",
        verifiedVisit: true,
      },
      {
        authorName: "Dan R.",
        rating: 4,
        body: "Great junior rates and the short course is ideal for new players. Range gets crowded on weekends.",
        verifiedVisit: true,
      },
      {
        authorName: "Priya K.",
        rating: 5,
        body: "PGA Jr. League here was the highlight of my son's summer. Well organized, friendly families.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Lone Star Junior Golf Academy",
    type: "academy",
    description:
      "Year-round junior development academy with indoor simulators, TrackMan bays, and a competitive player pathway. Small-group classes capped at 6 students per coach.",
    address: "1810 Champions Way",
    city: "Plano",
    state: "TX",
    zip: "75024",
    lat: 33.0759,
    lng: -96.8236,
    phone: "(972) 555-0188",
    website: "https://example.com/lone-star-academy",
    hours: "Mon–Fri 3pm–9pm, Sat–Sun 8am–6pm",
    ageMin: 6,
    ageMax: 18,
    skillLevels: "beginner,intermediate,competitive",
    priceTier: 3,
    programs: "lessons,clinics,camps",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-12),
    reviews: [
      {
        authorName: "Carlos M.",
        rating: 5,
        body: "My daughter went from shooting 110 to breaking 90 in one year on their competitive track. Structured, data-driven, worth every penny.",
        verifiedVisit: true,
      },
      {
        authorName: "Jen W.",
        rating: 4,
        body: "Excellent coaching. Only knock is the waitlist — sign up early for summer camps.",
        verifiedVisit: true,
      },
    ],
  },
  {
    name: "Coach Dana Whitfield, PGA",
    type: "instructor",
    description:
      "PGA professional specializing in junior instruction (ages 5–17). U.S. Kids Golf Top 50 Master Kids Teacher. Beginner-friendly group clinics Saturday mornings and private lessons weekday evenings.",
    address: "Pecan Hollow Golf Course, 4501 E 14th St",
    city: "Plano",
    state: "TX",
    zip: "75074",
    lat: 33.0151,
    lng: -96.6601,
    phone: "(469) 555-0117",
    website: "https://example.com/coach-dana",
    hours: "By appointment",
    ageMin: 5,
    ageMax: 17,
    skillLevels: "beginner,intermediate",
    priceTier: 2,
    programs: "lessons,clinics",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-8),
    reviews: [
      {
        authorName: "Aisha B.",
        rating: 5,
        body: "Dana is incredible with nervous beginners. My twins (6) had never held a club; after four lessons they ask to practice putting in the hallway.",
        verifiedVisit: true,
      },
      {
        authorName: "Tom H.",
        rating: 5,
        body: "Patient, encouraging, and great at communicating with parents about progress.",
        verifiedVisit: true,
      },
      {
        authorName: "Grace L.",
        rating: 4,
        body: "Saturday clinics fill up fast. Book two weeks out.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Cowtown Driving Range & Practice Center",
    type: "range",
    description:
      "60-bay double-deck range with a free junior tee bucket every Sunday. Short-game area, putting green, and $5 junior buckets all week.",
    address: "2900 Stockyard Blvd",
    city: "Fort Worth",
    state: "TX",
    zip: "76164",
    lat: 32.7886,
    lng: -97.3469,
    phone: "(817) 555-0163",
    website: "https://example.com/cowtown-range",
    hours: "Daily 7am–10pm",
    ageMin: 4,
    ageMax: 18,
    skillLevels: "beginner,intermediate,competitive",
    priceTier: 1,
    programs: "lessons,clinics",
    verified: true,
    claimed: false,
    source: "imported",
    lastVerifiedAt: daysFromNow(-45),
    reviews: [
      {
        authorName: "Marcus J.",
        rating: 5,
        body: "Free Sunday junior buckets is the best deal in DFW. Staff is great with kids.",
        verifiedVisit: true,
      },
      {
        authorName: "Elena S.",
        rating: 4,
        body: "Good lights for evening practice after school. Wish the short-game area were bigger.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Prairie Creek Golf Course",
    type: "course",
    description:
      "Municipal 18-hole course with junior rates ($12 for 9 holes) and a First Tee chapter on site. Friendly to walk-on juniors after school.",
    address: "700 Prairie Creek Pkwy",
    city: "Arlington",
    state: "TX",
    zip: "76010",
    lat: 32.7244,
    lng: -97.1149,
    phone: "(817) 555-0129",
    website: "https://example.com/prairie-creek",
    hours: "Daily 6am–dusk",
    ageMin: 6,
    ageMax: 18,
    skillLevels: "beginner,intermediate",
    priceTier: 1,
    programs: "lessons,leagues,tournaments",
    verified: false,
    claimed: false,
    source: "imported",
    lastVerifiedAt: null,
    reviews: [
      {
        authorName: "Robert F.",
        rating: 4,
        body: "Affordable and welcoming to kids. Course conditions vary but the value is unbeatable.",
        verifiedVisit: true,
      },
    ],
  },
  {
    name: "Bluebonnet Ridge Country Club Junior Program",
    type: "course",
    description:
      "Semi-private club with a serious competitive junior pathway: weekly tournaments, college-prep coaching, and reciprocal access to three sister courses. Non-member junior memberships available.",
    address: "9100 Bluebonnet Ridge Dr",
    city: "Southlake",
    state: "TX",
    zip: "76092",
    lat: 32.9546,
    lng: -97.1417,
    phone: "(817) 555-0171",
    website: "https://example.com/bluebonnet-ridge",
    hours: "Tue–Sun 6:30am–8pm",
    ageMin: 8,
    ageMax: 18,
    skillLevels: "intermediate,competitive",
    priceTier: 3,
    programs: "lessons,leagues,tournaments,camps",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-5),
    reviews: [
      {
        authorName: "Steph N.",
        rating: 5,
        body: "If your kid is serious about tournament golf, this is the place in DFW. Three current students signed D1 last year.",
        verifiedVisit: true,
      },
      {
        authorName: "Victor P.",
        rating: 4,
        body: "Top-notch program but expect a real commitment — and real cost.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Coach Marcus Lee — Junior Short Game Lab",
    type: "instructor",
    description:
      "Former mini-tour player focused exclusively on short game and putting for juniors 10+. Video analysis included in every lesson. Popular with competitive players prepping for tournament season.",
    address: "Cowtown Driving Range, 2900 Stockyard Blvd",
    city: "Fort Worth",
    state: "TX",
    zip: "76164",
    lat: 32.789,
    lng: -97.3461,
    phone: "(682) 555-0195",
    website: "https://example.com/marcus-lee-golf",
    hours: "Wed–Sun by appointment",
    ageMin: 10,
    ageMax: 18,
    skillLevels: "intermediate,competitive",
    priceTier: 2,
    programs: "lessons",
    verified: false,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-30),
    reviews: [
      {
        authorName: "Dana O.",
        rating: 5,
        body: "My son dropped four strokes in two months, all inside 100 yards. Marcus makes practice feel like a game.",
        verifiedVisit: true,
      },
    ],
  },
  {
    name: "Junior Links Summer Camp at Eagle Crest",
    type: "camp",
    description:
      "Weekly summer day camps (Mon–Fri, 9am–2pm) for ages 7–14. Daily on-course play, rules and etiquette, lunch included. Beginner and intermediate tracks.",
    address: "5500 Eagle Crest Blvd",
    city: "Irving",
    state: "TX",
    zip: "75063",
    lat: 32.9192,
    lng: -96.9919,
    phone: "(972) 555-0156",
    website: "https://example.com/eagle-crest-camp",
    hours: "Summer sessions, Mon–Fri 9am–2pm",
    ageMin: 7,
    ageMax: 14,
    skillLevels: "beginner,intermediate",
    priceTier: 2,
    programs: "camps",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-15),
    reviews: [
      {
        authorName: "Hannah G.",
        rating: 5,
        body: "Best camp we've tried in three summers. Counselor-to-camper ratio is great and the kids actually play the course every day.",
        verifiedVisit: true,
      },
      {
        authorName: "Will D.",
        rating: 4,
        body: "Well run. Sells out by April, so register early.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Oak Cliff Golf Learning Center",
    type: "academy",
    description:
      "Nonprofit learning center bringing golf to south Dallas youth. Sliding-scale pricing, free loaner clubs, and after-school programs with homework help built in.",
    address: "3110 W Kiest Blvd",
    city: "Dallas",
    state: "TX",
    zip: "75233",
    lat: 32.6932,
    lng: -96.8614,
    phone: "(214) 555-0102",
    website: "https://example.com/oak-cliff-glc",
    hours: "Mon–Fri 3pm–7pm, Sat 9am–4pm",
    ageMin: 5,
    ageMax: 17,
    skillLevels: "beginner,intermediate",
    priceTier: 1,
    programs: "lessons,clinics,leagues",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-10),
    reviews: [
      {
        authorName: "Tamika R.",
        rating: 5,
        body: "This place is a gem. Sliding-scale pricing made golf possible for us, and the coaches genuinely care about the kids beyond golf.",
        verifiedVisit: true,
      },
      {
        authorName: "Jorge V.",
        rating: 5,
        body: "Free loaner clubs removed the biggest barrier for us to try the sport.",
        verifiedVisit: true,
      },
    ],
  },
  {
    name: "North Texas Junior Golf Tour HQ",
    type: "academy",
    description:
      "Home base of the region's largest independent junior tour — 22 events per season across DFW. Membership includes a season schedule, live scoring, and a year-end championship.",
    address: "1200 Tour Plaza, Suite 210",
    city: "Frisco",
    state: "TX",
    zip: "75034",
    lat: 33.1507,
    lng: -96.8236,
    phone: "(214) 555-0190",
    website: "https://example.com/ntjgt",
    hours: "Office: Mon–Fri 9am–5pm",
    ageMin: 8,
    ageMax: 18,
    skillLevels: "intermediate,competitive",
    priceTier: 2,
    programs: "tournaments,leagues",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-3),
    reviews: [
      {
        authorName: "Kim A.",
        rating: 4,
        body: "Well-run events with fair pairings by age and score. Communication before events could be a bit earlier.",
        verifiedVisit: true,
      },
    ],
  },
  {
    name: "Riverside Par-3 & Footgolf",
    type: "course",
    description:
      "Lighted 9-hole par-3 — the perfect first 'real course' for young juniors. Kids 12 and under play free with an adult on weekdays.",
    address: "801 Riverside Dr",
    city: "Grand Prairie",
    state: "TX",
    zip: "75050",
    lat: 32.7593,
    lng: -97.0067,
    phone: "(972) 555-0148",
    website: "https://example.com/riverside-par3",
    hours: "Daily 8am–10pm (lighted)",
    ageMin: 4,
    ageMax: 18,
    skillLevels: "beginner",
    priceTier: 1,
    programs: "lessons",
    verified: false,
    claimed: false,
    source: "imported",
    lastVerifiedAt: null,
    reviews: [
      {
        authorName: "Beth C.",
        rating: 5,
        body: "Took my 5-year-old for her first ever round here. Staff gave her a free scorecard and made a huge deal of her first putt. We'll be back weekly.",
        verifiedVisit: true,
      },
      {
        authorName: "Omar Z.",
        rating: 4,
        body: "Casual, cheap, and lighted at night. Exactly what beginner kids need.",
        verifiedVisit: false,
      },
    ],
  },
  {
    name: "Coach Emily Sato — Girls Golf DFW",
    type: "instructor",
    description:
      "LPGA teaching professional running girls-only clinics and an LPGA*USGA Girls Golf chapter. Emphasis on confidence, friendships, and tournament readiness.",
    address: "Trinity Pines Golf Club, 4200 Riverbend Dr",
    city: "Dallas",
    state: "TX",
    zip: "75204",
    lat: 32.8118,
    lng: -96.77,
    phone: "(214) 555-0177",
    website: "https://example.com/girls-golf-dfw",
    hours: "Sat 9am–12pm clinics; privates by appointment",
    ageMin: 6,
    ageMax: 17,
    skillLevels: "beginner,intermediate,competitive",
    priceTier: 2,
    programs: "lessons,clinics,leagues",
    verified: true,
    claimed: true,
    source: "claimed",
    lastVerifiedAt: daysFromNow(-7),
    reviews: [
      {
        authorName: "Nicole D.",
        rating: 5,
        body: "My daughter found her people here. The girls-only environment made all the difference for her confidence.",
        verifiedVisit: true,
      },
      {
        authorName: "Sarah M.",
        rating: 5,
        body: "Emily is a phenomenal coach and role model. Clinics are energetic and welcoming.",
        verifiedVisit: true,
      },
    ],
  },
];

const events = [
  {
    title: "NTJGT Spring Championship — Trinity Pines",
    description:
      "Season-opening 18-hole stroke play championship of the North Texas Junior Golf Tour. Live scoring, tee gifts, and trophies by division.",
    eventType: "tournament",
    venueName: "Trinity Pines Golf Club",
    address: "4200 Riverbend Dr",
    city: "Dallas",
    state: "TX",
    lat: 32.8121,
    lng: -96.7695,
    dateStart: daysFromNow(12, 7),
    dateEnd: daysFromNow(12, 15),
    ageDivisions: "Boys/Girls 10–12, 13–15, 16–18",
    skillLevel: "competitive",
    entryFee: 8500,
    format: "Stroke play (18 holes)",
    registrationUrl: "https://example.com/ntjgt/spring-championship",
    registrationDeadline: daysFromNow(7),
    maxParticipants: 96,
    spotsRemaining: 14,
    organizerName: "North Texas Junior Golf Tour",
    tourAffiliation: "NTJGT",
  },
  {
    title: "Beginner Saturday Clinic with Coach Dana",
    description:
      "60-minute group clinic for brand-new juniors. Clubs provided. Parents welcome to watch from the patio. Grip, stance, and first swings — ends with a putting contest.",
    eventType: "clinic",
    venueName: "Pecan Hollow Golf Course",
    address: "4501 E 14th St",
    city: "Plano",
    state: "TX",
    lat: 33.0151,
    lng: -96.6601,
    dateStart: daysFromNow(4, 9),
    dateEnd: daysFromNow(4, 10),
    ageDivisions: "Ages 5–10",
    skillLevel: "beginner",
    entryFee: 2500,
    format: "Group clinic",
    registrationUrl: "https://example.com/coach-dana/saturday-clinic",
    registrationDeadline: daysFromNow(3),
    maxParticipants: 8,
    spotsRemaining: 3,
    organizerName: "Coach Dana Whitfield, PGA",
    tourAffiliation: null,
  },
  {
    title: "Drive, Chip & Putt Local Qualifier — Fort Worth",
    description:
      "Official local qualifier for the Drive, Chip & Putt Championship. Free entry. Top finishers in each division advance to the subregional.",
    eventType: "qualifier",
    venueName: "Prairie Creek Golf Course",
    address: "700 Prairie Creek Pkwy",
    city: "Arlington",
    state: "TX",
    lat: 32.7244,
    lng: -97.1149,
    dateStart: daysFromNow(26, 8),
    dateEnd: daysFromNow(26, 14),
    ageDivisions: "Boys/Girls 7–9, 10–11, 12–13, 14–15",
    skillLevel: "all",
    entryFee: 0,
    format: "Skills competition",
    registrationUrl: "https://example.com/dcp/fort-worth-qualifier",
    registrationDeadline: daysFromNow(19),
    maxParticipants: 120,
    spotsRemaining: 41,
    organizerName: "Drive, Chip & Putt",
    tourAffiliation: "Drive Chip & Putt",
  },
  {
    title: "Parent/Child 9-Hole Scramble",
    description:
      "Relaxed two-person scramble for parents and juniors of any skill level. Closest-to-pin and longest-putt contests. Pizza dinner included after the round.",
    eventType: "scramble",
    venueName: "Riverside Par-3 & Footgolf",
    address: "801 Riverside Dr",
    city: "Grand Prairie",
    state: "TX",
    lat: 32.7593,
    lng: -97.0067,
    dateStart: daysFromNow(9, 16),
    dateEnd: daysFromNow(9, 19),
    ageDivisions: "All ages (junior + adult team)",
    skillLevel: "all",
    entryFee: 4000,
    format: "2-person scramble (9 holes)",
    registrationUrl: "https://example.com/riverside/parent-child-scramble",
    registrationDeadline: daysFromNow(7),
    maxParticipants: 36,
    spotsRemaining: 8,
    organizerName: "Riverside Par-3",
    tourAffiliation: null,
  },
  {
    title: "Summer Camp Week 1 — Eagle Crest",
    description:
      "First week of summer day camp. Daily on-course play, short-game games, rules & etiquette, lunch included. Beginner and intermediate tracks run in parallel.",
    eventType: "camp",
    venueName: "Eagle Crest Golf Club",
    address: "5500 Eagle Crest Blvd",
    city: "Irving",
    state: "TX",
    lat: 32.9192,
    lng: -96.9919,
    dateStart: daysFromNow(18, 9),
    dateEnd: daysFromNow(22, 14),
    ageDivisions: "Ages 7–14",
    skillLevel: "beginner",
    entryFee: 32500,
    format: "Day camp (Mon–Fri)",
    registrationUrl: "https://example.com/eagle-crest-camp/week-1",
    registrationDeadline: daysFromNow(11),
    maxParticipants: 40,
    spotsRemaining: 6,
    organizerName: "Junior Links Summer Camp",
    tourAffiliation: null,
  },
  {
    title: "Girls Golf DFW — Spring Skills Social",
    description:
      "Girls-only afternoon of skills stations, music, and a 3-hole on-course finish. New players welcome; clubs provided. LPGA*USGA Girls Golf chapter event.",
    eventType: "clinic",
    venueName: "Trinity Pines Golf Club",
    address: "4200 Riverbend Dr",
    city: "Dallas",
    state: "TX",
    lat: 32.8121,
    lng: -96.7695,
    dateStart: daysFromNow(6, 13),
    dateEnd: daysFromNow(6, 16),
    ageDivisions: "Girls 6–17",
    skillLevel: "all",
    entryFee: 1500,
    format: "Skills stations + 3 holes",
    registrationUrl: "https://example.com/girls-golf-dfw/spring-social",
    registrationDeadline: daysFromNow(4),
    maxParticipants: 30,
    spotsRemaining: 12,
    organizerName: "Girls Golf DFW",
    tourAffiliation: "LPGA*USGA Girls Golf",
  },
  {
    title: "PGA Jr. League Summer Season Registration Rally",
    description:
      "Meet the coaches, try the format, and register for the summer PGA Jr. League season. Scrimmage holes open all morning — bring the whole family.",
    eventType: "league",
    venueName: "Trinity Pines Golf Club",
    address: "4200 Riverbend Dr",
    city: "Dallas",
    state: "TX",
    lat: 32.8121,
    lng: -96.7695,
    dateStart: daysFromNow(14, 9),
    dateEnd: daysFromNow(14, 12),
    ageDivisions: "Ages 7–13",
    skillLevel: "all",
    entryFee: 0,
    format: "Open house + scrimmage",
    registrationUrl: "https://example.com/trinity-pines/pga-jr-league",
    registrationDeadline: daysFromNow(13),
    maxParticipants: null,
    spotsRemaining: null,
    organizerName: "Trinity Pines Golf Club",
    tourAffiliation: "PGA Jr. League",
  },
  {
    title: "NTJGT Major #2 — Bluebonnet Ridge Invitational",
    description:
      "36-hole invitational over two days at DFW's premier junior tournament venue. AJGA PBE stars available. Field limited to players with established tournament records.",
    eventType: "tournament",
    venueName: "Bluebonnet Ridge Country Club",
    address: "9100 Bluebonnet Ridge Dr",
    city: "Southlake",
    state: "TX",
    lat: 32.9546,
    lng: -97.1417,
    dateStart: daysFromNow(33, 7),
    dateEnd: daysFromNow(34, 16),
    ageDivisions: "Boys/Girls 13–15, 16–18",
    skillLevel: "competitive",
    entryFee: 14500,
    format: "Stroke play (36 holes, 2 days)",
    registrationUrl: "https://example.com/ntjgt/bluebonnet-invitational",
    registrationDeadline: daysFromNow(24),
    maxParticipants: 78,
    spotsRemaining: 22,
    organizerName: "North Texas Junior Golf Tour",
    tourAffiliation: "NTJGT",
  },
  {
    title: "Free First Tee Intro Day — Oak Cliff",
    description:
      "Completely free introduction to golf for kids who've never played. Loaner clubs, snacks, and a parent info session about year-round sliding-scale programs.",
    eventType: "clinic",
    venueName: "Oak Cliff Golf Learning Center",
    address: "3110 W Kiest Blvd",
    city: "Dallas",
    state: "TX",
    lat: 32.6932,
    lng: -96.8614,
    dateStart: daysFromNow(8, 10),
    dateEnd: daysFromNow(8, 13),
    ageDivisions: "Ages 5–17",
    skillLevel: "beginner",
    entryFee: 0,
    format: "Open intro day",
    registrationUrl: "https://example.com/oak-cliff-glc/intro-day",
    registrationDeadline: null,
    maxParticipants: 60,
    spotsRemaining: 27,
    organizerName: "Oak Cliff Golf Learning Center",
    tourAffiliation: "First Tee",
  },
  {
    title: "College Golf Recruiting Night (Parents & Juniors 13+)",
    description:
      "Panel with two college coaches and a current D1 player: timelines, tournament resumes, NCAA rules, and what coaches actually watch for. Q&A and free recruiting checklist.",
    eventType: "showcase",
    venueName: "Lone Star Junior Golf Academy",
    address: "1810 Champions Way",
    city: "Plano",
    state: "TX",
    lat: 33.0759,
    lng: -96.8236,
    dateStart: daysFromNow(21, 18),
    dateEnd: daysFromNow(21, 20),
    ageDivisions: "Juniors 13–18 + parents",
    skillLevel: "competitive",
    entryFee: 0,
    format: "Panel + Q&A",
    registrationUrl: "https://example.com/lone-star/recruiting-night",
    registrationDeadline: daysFromNow(20),
    maxParticipants: 80,
    spotsRemaining: 35,
    organizerName: "Lone Star Junior Golf Academy",
    tourAffiliation: null,
  },
];

async function main() {
  // In production the seed runs on every boot (see start:prod); only
  // reseed when the database is empty unless --force is passed.
  const force = process.argv.includes("--force");
  if (!force && (await prisma.listing.count()) > 0) {
    console.log("Database already seeded; skipping (use --force to reseed).");
    return;
  }

  await prisma.review.deleteMany();
  await prisma.event.deleteMany();
  await prisma.listing.deleteMany();

  for (const { reviews, ...listing } of listings) {
    await prisma.listing.create({
      data: { ...listing, reviews: { create: reviews } },
    });
  }
  for (const event of events) {
    await prisma.event.create({ data: event });
  }

  const counts = {
    listings: await prisma.listing.count(),
    reviews: await prisma.review.count(),
    events: await prisma.event.count(),
  };
  console.log("Seeded:", counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
